#!/usr/bin/env php
<?php

use Arunabraham\TestSqliteKeyValue\{
    SchemaGenerator,
    FileToData,
    InsertData,
    DataStream
};
use Clue\React\SQLite\DatabaseInterface;
use Clue\React\SQLite\Factory;

use function React\Async\await;

require __DIR__ . '/vendor/autoload.php';

$fileData = new FileToData;
$sqlite = new Factory;
$dbFile = 'test.db';

//Create Database
$sqlite->open($dbFile)->then(function (DatabaseInterface $db) use ($fileData) {
    (new SchemaGenerator)($db);
    return $db;
})->then(function(DatabaseInterface $db) use($fileData){
    (new InsertData)($db, $fileData->getData());
   return $db;
})->then(function(DatabaseInterface $db){
    $dbStream = (new DataStream)($db);
    $dbStream->then(function ($result) {
        foreach($result as $row) {
            var_dump($row);
        }
    });
    $db->quit();
});
